apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "29.0.2"

    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    defaultConfig {
        applicationId "net.ifeu.edicards"
        minSdkVersion 24
        targetSdkVersion 26
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
        exclude("META-INF/*.kotlin_module")
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.android.support:support-v4:24.2.1'
    implementation 'com.google.code.gson:gson:2.3.1'
    implementation 'com.google.code.gson:gson:2.3.1'
    implementation 'com.google.code.gson:gson:2.2.2'
    implementation 'com.amitshekhar.android:android-networking:1.0.0'
    implementation files('libs/activation.jar')
    implementation files('libs/additionnal.jar')
    //implementation files('libs/commons-codec-1.10.jar')
    implementation files('libs/commons-logging-1.2.jar')
    implementation files('libs/fluent-hc-4.5.6.jar')
    implementation files('libs/httpclient-4.5.6.jar')
    implementation files('libs/httpclient-cache-4.5.6.jar')
    implementation files('libs/httpclient-win-4.5.6.jar')
    implementation files('libs/httpcore-4.4.10.jar')
    implementation files('libs/httpmime-4.5.6.jar')
    implementation files('libs/itextpdf-5.4.0.jar')
    implementation files('libs/ksoap2-android-assembly-2.3-jar-with-dependencies.jar')
    implementation files('libs/mail.jar')
    implementation files('libs/Parse-1.2.3.jar')
    implementation files('libs/StarIOPort3.1.jar')
    implementation files('libs/woosimprinter_bt.jar')

    implementation 'org.apache.poi:poi-ooxml:3.10-FINAL'
    implementation 'org.apache.poi:poi-scratchpad:3.10-FINAL'
    implementation 'org.apache.commons:commons-text:1.9'
    compile "org.apache.commons:commons-csv:1.5"
    implementation 'com.google.zxing:core:3.4.1'
    implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
    implementation 'commons-net:commons-net:3.5'

    //implementation 'androidx.multidex:multidex:2.0.1'
}